# Generated by Django 4.0.3 on 2022-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TDocument_Type', models.CharField(max_length=100)),
                ('document', models.PositiveIntegerField()),
                ('names', models.CharField(max_length=200)),
                ('last_names', models.CharField(max_length=200)),
                ('hobbie', models.CharField(max_length=100)),
            ],
        ),
    ]
